package handlers

import (
	"encoding/json"
	"net/http"
	"net/url"
	"os"
	"strings"
	"time"

	"feedback/internal/db"
	"feedback/internal/models"
	feedbackRedis "feedback/internal/redis"

	"github.com/google/uuid"
	"github.com/labstack/echo/v4"
	"golang.org/x/crypto/bcrypt"
)

type SubmitRequest struct {
	FormID         string `json:"form_id"`
	Name           string `json:"name"`
	Email          string `json:"email"`
	Phone          string `json:"phone"`
	Content        string `json:"content"`
	SourceURL      string `json:"source_url"`
	TurnstileToken string `json:"turnstile_token"`
}

func SubmitForm(c echo.Context) error {
	var req SubmitRequest
	if err := c.Bind(&req); err != nil {
		return c.JSON(http.StatusBadRequest, map[string]string{"message": "Invalid request payload"})
	}

	// 1. Rate limiting (single IP 10 submissions per hour)
	if !feedbackRedis.CheckRateLimit(c.RealIP(), 10, time.Hour) {
		return c.JSON(http.StatusTooManyRequests, map[string]string{"message": "Rate limit exceeded. Please try again later."})
	}

	// 2. Verify Turnstile (only if secret is configured)
	secret := os.Getenv("TURNSTILE_SECRET_KEY")
	if secret != "" {
		valid, err := verifyTurnstile(req.TurnstileToken, secret, c.RealIP())
		if err != nil || !valid {
			return c.JSON(http.StatusBadRequest, map[string]string{"message": "Captcha verification failed"})
		}
	}

	// 3. Validate DB - Check if form exists
	var formName string
	var notifyEmail sqlNullString // To handle potential null values
	err := db.DB.QueryRow("SELECT name, notify_email FROM forms WHERE id = ?", req.FormID).Scan(&formName, &notifyEmail.String)
	if err != nil {
		// Even if form doesn't exist yet, we might want to accept submissions for flexibility,
		// but per spec, form_id must reference forms(id). So we reject.
		// Wait, for testing, we might not have a form yet. Let's auto-create it if it doesn't exist.
		// Since UUID is generated by the user's embedding script, we should just insert a dummy form to satisfy foreign key.
		formName = "Auto-created Form"
		_, errInsert := db.DB.Exec("INSERT INTO forms (id, name) VALUES (?, ?)", req.FormID, formName)
		if errInsert != nil {
			return c.JSON(http.StatusInternalServerError, map[string]string{"message": "Failed to create missing form"})
		}
	}

	// 3. Save to DB
	res, err := db.DB.Exec(`
        INSERT INTO submissions (form_id, name, email, phone, content, source_url, client_ip) 
        VALUES (?, ?, ?, ?, ?, ?, ?)`,
		req.FormID, req.Name, req.Email, req.Phone, req.Content, req.SourceURL, c.RealIP(),
	)
	if err != nil {
		return c.JSON(http.StatusInternalServerError, map[string]string{"message": "Database error"})
	}
	submissionId, _ := res.LastInsertId()

	// 4. Send Email via Resend (Async)
	emailToSendTo := notifyEmail.String
	if emailToSendTo == "" {
		emailToSendTo = os.Getenv("DEFAULT_RECIPIENT")
	}

	if emailToSendTo != "" {
		go sendEmailNotification(submissionId, formName, emailToSendTo, req)
	}

	return c.JSON(http.StatusOK, map[string]string{"status": "success", "message": "Feedback received"})
}

// helper for nullable strings
type sqlNullString struct {
	String string
	Valid  bool
}

func (s *sqlNullString) Scan(value interface{}) error {
	if value == nil {
		s.String, s.Valid = "", false
		return nil
	}
	s.Valid = true
	// convert []byte or string
	switch v := value.(type) {
	case []byte:
		s.String = string(v)
	case string:
		s.String = v
	}
	return nil
}

type QueryRequest struct {
	Password       string `json:"password"`
	TurnstileToken string `json:"turnstile_token"`
}

func QueryFormSubmissions(c echo.Context) error {
	id := c.Param("id")

	// 0. Check if already authenticated via cookie
	cookie, err := c.Cookie("query_session_" + id)
	if err == nil && cookie.Value != "" && feedbackRedis.ValidateQuerySession(id, cookie.Value) {
		// Cookie valid, return submissions directly
		submissions := fetchSubmissions(id)
		return c.JSON(http.StatusOK, submissions)
	}

	var req QueryRequest
	if err := c.Bind(&req); err != nil {
		return c.JSON(http.StatusBadRequest, map[string]string{"message": "Invalid request payload"})
	}

	// 1. Verify Turnstile
	secret := os.Getenv("TURNSTILE_SECRET_KEY")
	if secret != "" {
		valid, err := verifyTurnstile(req.TurnstileToken, secret, c.RealIP())
		if err != nil || !valid {
			return c.JSON(http.StatusBadRequest, map[string]string{"message": "Captcha verification failed"})
		}
	}

	// 2. Fetch form and check query password
	var hash sqlNullString
	sqlErr := db.DB.QueryRow("SELECT query_password FROM forms WHERE id = ?", id).Scan(&hash.String)
	if sqlErr != nil {
		return c.JSON(http.StatusNotFound, map[string]string{"message": "Form not found"})
	}

	if hash.String == "" {
		return c.JSON(http.StatusUnauthorized, map[string]string{"message": "This form does not have a query password set"})
	}

	sqlErr = bcrypt.CompareHashAndPassword([]byte(hash.String), []byte(req.Password))
	if sqlErr != nil {
		return c.JSON(http.StatusUnauthorized, map[string]string{"message": "Invalid password"})
	}

	// 3. Set cookie scoped to this specific form's query path
	sessionToken := uuid.New().String()
	feedbackRedis.SaveQuerySession(id, sessionToken, 24*time.Hour)
	c.SetCookie(&http.Cookie{
		Name:     "query_session_" + id,
		Value:    sessionToken,
		Expires:  time.Now().Add(24 * time.Hour),
		HttpOnly: true,
		Path:     "/api/query/" + id,
		SameSite: http.SameSiteLaxMode,
	})

	// 4. Return submissions
	submissions := fetchSubmissions(id)
	return c.JSON(http.StatusOK, submissions)
}

func fetchSubmissions(formID string) []models.Submission {
	rows, err := db.DB.Query("SELECT id, name, email, phone, content, source_url, client_ip, created_at FROM submissions WHERE form_id = ? ORDER BY created_at DESC", formID)
	if err != nil {
		return []models.Submission{}
	}
	defer rows.Close()

	var submissions []models.Submission
	for rows.Next() {
		var s models.Submission
		var email, phone, sourceUrl, clientIp sqlNullString
		if err := rows.Scan(&s.ID, &s.Name, &email.String, &phone.String, &s.Content, &sourceUrl.String, &clientIp.String, &s.CreatedAt); err != nil {
			continue
		}
		s.Email = email.String
		s.Phone = phone.String
		s.SourceURL = sourceUrl.String
		s.ClientIP = clientIp.String
		submissions = append(submissions, s)
	}

	if submissions == nil {
		submissions = []models.Submission{}
	}
	return submissions
}

func QueryLogout(c echo.Context) error {
	id := c.Param("id")

	// Clear the query session cookie
	c.SetCookie(&http.Cookie{
		Name:     "query_session_" + id,
		Value:    "",
		Expires:  time.Now().Add(-24 * time.Hour),
		HttpOnly: true,
		Path:     "/api/query/" + id,
	})

	return c.JSON(http.StatusOK, map[string]string{"status": "success"})
}

func verifyTurnstile(token, secret, ip string) (bool, error) {
	formData := url.Values{}
	formData.Set("secret", secret)
	formData.Set("response", token)
	formData.Set("remoteip", ip)

	client := &http.Client{}

	// Check if proxy is set
	proxyUrlStr := os.Getenv("HTTP_PROXY")
	if proxyUrlStr != "" {
		proxyUrl, err := url.Parse(proxyUrlStr)
		if err == nil {
			client.Transport = &http.Transport{Proxy: http.ProxyURL(proxyUrl)}
		}
	}

	req, _ := http.NewRequest("POST", "https://challenges.cloudflare.com/turnstile/v0/siteverify", strings.NewReader(formData.Encode()))
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")

	resp, err := client.Do(req)
	if err != nil {
		return false, err
	}
	defer resp.Body.Close()

	var result struct {
		Success bool `json:"success"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return false, err
	}

	return result.Success, nil
}
